name=sdFat32
version=1.0.0
author=Surya Poudel
maintainer=poudel.surya2011@gmail.com
sentence=FAT32 library for SD card using SPI mode.
paragraph=sdFat32 is a lightweight, bare-metal FAT32 filesystem library designed for embedded systems. It enables seamless read/write access to SD cards using the FAT32 file system, with minimal dependencies and a focus on performance and portability. Ideal for microcontrollers and resource-constrained environments.
category=Other
architectures=*
